/**
 * FirstQuadrant API
 * The FirstQuadrant API is used to interact with FirstQuadrant programmatically. We also have SDKs available (coming soon).
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: inquiry@firstquadrant.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Success { 
    success: Success.SuccessEnum | null;
}
export namespace Success {
    export type SuccessEnum = 'true';
    export const SuccessEnum = {
        True: 'true' as SuccessEnum
    };
}


