# coding: utf-8

"""
    FirstQuadrant API

    The FirstQuadrant API is used to interact with FirstQuadrant programmatically. We also have SDKs available (coming soon).  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Contact: inquiry@firstquadrant.ai
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.success import Success
from openapi_client import configuration


class TestSuccess(unittest.TestCase):
    """Success unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
