# coding: utf-8

"""
    FirstQuadrant API

    The FirstQuadrant API is used to interact with FirstQuadrant programmatically. We also have SDKs available (coming soon).  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Contact: inquiry@firstquadrant.ai
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.incoming_webhooks_mark_conversations_as_won.post import IncomingWebhooksMarkConversationsAsWonPost


class IncomingWebhooksApi(
    IncomingWebhooksMarkConversationsAsWonPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
