name: Generate SDKs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/generate-sdk.yml
jobs:
  generate-sdks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Generate SDKs
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download OpenAPI spec
        run: |
          curl -o openapi.yml https://firstquadrant-ai.github.io/docs/openapi.yml

      - name: Generate Go Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: go
          openapi-file: openapi.yml

      - name: Generate PHP Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-file: openapi.yml

      - name: Generate Python Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          openapi-file: openapi.yml

      - name: Generate Angular Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-angular
          openapi-file: openapi.yml

      - name: Generate Axios Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-axios
          openapi-file: openapi.yml

      - name: Generate Fetch Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-fetch
          openapi-file: openapi.yml

      - name: Commit changes to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(app): Generate updated SDKs"
