on:
  workflow_dispatch:
jobs:
  generate-sdks:
    runs-on: ubuntu-latest
    name: Generate SDKs
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Angular Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-angular
          openapi-url: https://firstquadrant-ai.github.io/docs/openapi.yml

      - name: Do something with the client
        run: |
          cd typescript-angular-client
