/* tslint:disable */
/* eslint-disable */
/**
 * FirstQuadrant API
 * The FirstQuadrant API is used to interact with FirstQuadrant programmatically. We also have SDKs available (coming soon).
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: inquiry@firstquadrant.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarkConversationAsWonBody
 */
export interface MarkConversationAsWonBody {
    /**
     * 
     * @type {any}
     * @memberof MarkConversationAsWonBody
     */
    email: any | null;
    /**
     * 
     * @type {any}
     * @memberof MarkConversationAsWonBody
     */
    idempotencyKey: any | null;
}

/**
 * Check if a given object implements the MarkConversationAsWonBody interface.
 */
export function instanceOfMarkConversationAsWonBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "idempotencyKey" in value;

    return isInstance;
}

export function MarkConversationAsWonBodyFromJSON(json: any): MarkConversationAsWonBody {
    return MarkConversationAsWonBodyFromJSONTyped(json, false);
}

export function MarkConversationAsWonBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkConversationAsWonBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'idempotencyKey': json['idempotencyKey'],
    };
}

export function MarkConversationAsWonBodyToJSON(value?: MarkConversationAsWonBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'idempotencyKey': value.idempotencyKey,
    };
}

